config/routes.rb
Rails.application.routes.draw do
  resources :option_shifts
  root 'home#index'
  get 'home/index'
  get 'home/about', :as => 'about'
  get 'home/contact', :as => 'contact'
  get 'home/administaracja', :as => 'administracja'
  get 'home/kalendarz', :as => 'kalendarz'
  get 'home/grafik', as: 'grafik'
  get 'kalendarz/new', to: 'kalendarz#new'
  post 'kalendarz/new', to: 'kalendarz#create'
  get 'kalendarz/edit/:id', to: 'kalendarz#edit', as: 'kalendarz_edit'
  post 'kalendarz/edit/:id', to: 'kalendarz#update'

  resources :employees
  resources :statuses
  resources :departments
  resources :shifts do
    resources :grafiks
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
    before_action :set_status, only:[:show, :edit, :update, :destroy]
    
    def index
        @statuses = Status.all
    end
    def show
    end
    def new
        @status = Status.new
    end
    def edit
    end
    
    def create
        @status = Status.new(status_params)
        
        respond_to do |format|
            if @status.save
                format.html { redirect_to @status, notice: 'Status was successfully created.' }
                format.json { render :show, status: :created, location: @status }
            else
                format.html { render :new }
                format.json { render json: @status.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def update
        respond_to do |format|
            if @status.update(status_params)
                format.html { redirect_to @status, notice: 'Status was successfully updated.' }
                format.json { render :show, status: :ok, location: @status }
            else
                format.html { render :edit }
                format.json { render json: @status.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @status.destroy
        respond_to do |format|
            format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:nazwa, :uprawnienia)
    end
end

app/views/statuses/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= yield(:title) %>
  </div>
  <div class="panel-body">
  <%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="input-group">
    <%= f.label :nazwa %><br>
    <%= f.text_field :nazwa, class: "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label :uprawnienia %><br>
    <%= f.text_field :uprawnienia, class: "form-control" %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>  
</div>
  <div class="panel-footer"><%= link_to "Powrót do listy", statuses_path %> | 
  <%= link_to "Panel administracyjny", administracja_path %></div>
</div>

app/views/statuses/edit.html.erb
<% provide(:title, "Edycja Statusu") %>
<%= render 'form' %>

app/views/statuses/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel administracyjny aplikacji - Lista statusów <span class="badge"><%= Status.count %></span></div>
  <div class="panel-body">
    Liczba statusów to: <%= Status.count %>
  </div>
  <div>
  <!-- Table -->
  <table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>Uprawnienia</th>
      <th>Liczba członków</th>
      <th colspan="3">Akcja:</th>
    </tr>
  </thead>

<tbody>
    <% @statuses.each do |status| %>
      <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
        <td><%= status.nazwa %></td>
        <td><%= status.uprawnienia %></td>
        <td><%= status.employees.count %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>
  <div class="panel-footer">
  <%= link_to 'Nowy Status', new_status_path %> |
  <%= link_to "Panel administracyjny", administracja_path %>
</div>
</div>

app/views/statuses/new.html.erb
<% provide(:title, "Nowy status") %>
<%= render 'form' %>

app/views/statuses/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Status:</div> 
  <div class="panel-body">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <p>
      <strong>Nazwa:</strong>
      <%= @status.nazwa %>
    </p>
    <p>
      <strong>Uprawnienia:</strong>
      <%= @status.uprawnienia %>
      </p>
  
  </div>
  <div class="panel-footer">
    <%= link_to 'Edytuj', edit_status_path(@status) %> | 
    <%= link_to 'Powrót do listy', statuses_path %> | 
    <%= link_to "Porót do administarcji", administracja_path %>
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Lista pracowników o statusie <%= @status.nazwa %></h3>
  </div>
  <div class="panel-body" id="list_product">
    <table class="admin_list table">
      <tr>
        <th>Email: </th>
        <th>Zmiana:</th>
        <th>Dział:</th>
      </tr>
      <div id="product_list">
    <% @status.employees.each do |employee| %>
      <tr class="<%= cycle('list_line_odd' , 'list_line_even' ) %>">
        <td><%= employee.email %></td>
        <td><%= employee.shift.nazwa %></td>
        <td><%= employee.department.nazwa %></td>
      </tr>
    <% end %>
    </div>
    </table>
  </div>
  <div class="panel-footer"><span class="label label-success">Pracownikó:  </span><span class="badge"><%= @status.employees.count %></span></div>
</div>