config/routes.rb
Rails.application.routes.draw do
  resources :option_shifts
  root 'home#index'
  get 'home/index'
  get 'home/about', :as => 'about'
  get 'home/contact', :as => 'contact'
  get 'home/administaracja', :as => 'administracja'
  get 'home/kalendarz', :as => 'kalendarz'
  get 'home/grafik', as: 'grafik'
  get 'kalendarz/new', to: 'kalendarz#new'
  post 'kalendarz/new', to: 'kalendarz#create'
  get 'kalendarz/edit/:id', to: 'kalendarz#edit', as: 'kalendarz_edit'
  post 'kalendarz/edit/:id', to: 'kalendarz#update'

  resources :employees
  resources :statuses
  resources :departments
  resources :shifts do
    resources :grafiks
  end

end

app/models/department.rb
class Department < ActiveRecord::Base
    validates_presence_of :nazwa, :message => "Musisz podać nazwę działu."
    has_many :employees
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    before_action :set_department, only:[:show, :edit, :update, :destroy]
    
    def index
        @departments = Department.all
    end
    def show
    end
    def new
        @department = Department.new
    end
    def edit
    end
    
    def create
        @department = Department.new(department_params)
        
        respond_to do |format|
            if @department.save
                format.html { redirect_to @department, notice: 'Departament został utworzony.' }
                format.json { render :show, status: :created, location: @department }
            else
                format.html { render :new }
                format.json { render json: @department.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def update
        respond_to do |format|
            if @department.update(department_params)
                format.html { redirect_to @department, notice: 'Departament został zaktualizowany.' }
                format.json { render :show, status: :ok, location: @department }
            else
                format.html { render :edit }
                format.json { render json: @department.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @department.destroy
        respond_to do |format|
            format.html { redirect_to department_url, notice: 'Departament został usunięty.' }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:nazwa)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= yield(:title) %>
  </div>
  <div class="panel-body">
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <% errors_count = @department.errors.count %>
      <% if errors_count == 1 %>
        <h2>1 błąd nie pozwala na przetworzenie formólarza:</h2>
      <% elsif errors_count < 5 %>
        <h2><%= errors_count %> błedy nie pozwalają na przetworzenie formólarza:</h2>
      <% else %>
        <h2><%= errors_count %> błedy nie pozwalają na przetworzenie formólarza:</h2>
      <% end %>
      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
      <%= f.label :nazwa, "Nazwa departamentu:" %><br />
      <%= f.text_field :nazwa %><br />
  </div>
  <div class="action">
      <%= f.submit %>
  </div>

<% end %>
</div>
  <div class="panel-footer"><%= link_to "Powrót do listy", departments_path %> | 
  <%= link_to "Panel administracyjny", administracja_path %></div>
</div>

app/views/departments/edit.html.erb
<% provide(:title, "Edycja departamentu") %>
<%= render 'form' %>

app/views/departments/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel administracyjny aplikacji - Lista departamentów. <span class="badge"><%= Department.count %></span></div>
  <div class="panel-body">
  </div>

  <!-- Table -->
  <table class="table">
        <tr>
            <th>Nazwa Departamentu:</th>
            <th>Liczba pracowników:</th>
            <th>Akcja:</th>
        </tr>
        <% @departments.each do |department| %>
          <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
              <td>
                  <%= department.nazwa %>
              </td>
              <td><%= department.employees.count %></td>
              <td class="list_actions" >
                  <%= link_to 'Show' , department %> | 
                  <%= link_to 'Edit' , edit_department_path(department) %> | 
                  <%= link_to 'Destroy' , department,
                  :confirm => 'Jesteś pewien?' ,
                  :method => :delete %>
              </td>
          </tr>
        <% end %>
    </table>
    <div class="panel-footer">
  <%= link_to 'Nowy Departament' , new_department_path %> |
<%= link_to "Porót do administarcji", administracja_path %>
  </div>
</div>
<br />

app/views/departments/new.html.erb
<% provide(:title, "Nowy departament") %>
<%= render 'form' %>

app/views/departments/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Departament:</div> 
  <div class="panel-body">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <p>
      <strong>Nazwa:</strong>
      <%= @department.nazwa %>
    </p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Edytuj', edit_department_path(@department) %> | 
    <%= link_to 'Powrót do listy', departments_path %> | 
    <%= link_to "Porót do administarcji", administracja_path %>
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Lista pracowników na dziale <%= @department.nazwa %></h3>
  </div>
  <div class="panel-body" id="list_product">
    <table class="admin_list table">
      <tr>
        <th>Email: </th>
        <th>Zmiana:</th>
        <th>Status:</th>
      </tr>
      <div id="product_list">
    <% @department.employees.each do |employee| %>
      <tr class="<%= cycle('list_line_odd' , 'list_line_even' ) %>">
        <td><%= employee.email %></td>
        <td><%= employee.shift.nazwa %></td>
        <td><%= employee.status.nazwa %></td>
      </tr>
    <% end %>
    </div>
    </table>
  </div>
  <div class="panel-footer"><span class="label label-success">Pracownikó:  </span><span class="badge"><%= @department.employees.count %></span></div>
</div>