config/routes.rb
Rails.application.routes.draw do
  resources :option_shifts
  root 'home#index'
  get 'home/index'
  get 'home/about', :as => 'about'
  get 'home/contact', :as => 'contact'
  get 'home/administaracja', :as => 'administracja'
  get 'home/kalendarz', :as => 'kalendarz'
  get 'home/grafik', as: 'grafik'
  get 'kalendarz/new', to: 'kalendarz#new'
  post 'kalendarz/new', to: 'kalendarz#create'
  get 'kalendarz/edit/:id', to: 'kalendarz#edit', as: 'kalendarz_edit'
  post 'kalendarz/edit/:id', to: 'kalendarz#update'

  resources :employees
  resources :statuses
  resources :departments
  resources :shifts do
    resources :grafiks
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end
  def administaracja
  end
  def kalendarz
  end
  def grafik
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#" id: logo>GRAFIK</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Strona główna", root_path %></li>
          <li><%= link_to "Administracja", administracja_path %></li>
          <li><%= link_to "O programie....", about_path %></li>
          <li><%= link_to "Kontakt z developerem", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    

app/views/home/administaracja.html.erb
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel administracyjny aplikacji</div>
  <div class="panel-body">
  </div>

  <!-- Table -->
  <table class="admin_list">
    <tr>
        <td><%= link_to "Pracownicy.", employees_path %></td>
        <td><span class="badge"><%= Employee.count %></span> pracowników</td>
    </tr>
    <tr>
        <td><%= link_to "Statusy pracowników.", statuses_path %></td>
        <td><span class="badge"><%= Status.count %></span> statusy</td>
    </tr>
    <tr>
        <td><%= link_to "Departamenty.", departments_path %></td>
        <td><span class="badge"><%= Department.count %></span> departamenty</td>
    </tr>
    <tr>
        <td><%= link_to "Zmiany.", shifts_path %></td>
        <td><span class="badge"><%= Shift.count %></span> zmiany</td>
    </tr>
  </table>
  <div class="panel-footer"><%= link_to "Strona główna.", root_path %></div>
</div>

app/views/home/contact.html.erb
<p>Maciej Sypniewski <a href="mailto:msypniewski511@gmail.com">Prześlij mi Email </a></p>

app/views/home/grafik.html.erb
<!-- Stack the columns on mobile by making one full-width and the other half-width -->
<div class="row">
    <div class="col-xs-12 col-md-3">
      <h2>Maciej Sypniewski</h2>
      <%= image_tag("zima.png", class: 'img-thumbnail') %><br /><br />
      <br />
      <hr />
      <br />
      <!-- Wyświetla legende użytych kolorów na kalendrzu. -->
      <div class="panel panel-primary">
       <div class="panel-heading">Legenda:</div> 
      <div class="panel-body">
        <table>
          <% OptionShift.all.each do |opcja| %>
            <tr style="color: <%= opcja.color %>">
              <td><%= opcja.option %></td>
              <td><%= opcja.description %></td>
            </tr>
          <% end %>
        </table>
      </div>
      </div>
      <!-- Główny kalendarz -->
      </div>
      <div class="col-xs12 col-md-6">
        <hr />
        <div class="calendar-container">
          <header>
            <div class="day"><% t = Time.now %><%= t.day %></div>
            <div class="month"><%= data_month(t.month) %></div>
          </header>
          <table class="calendar">
            <thead>
              <tr>
                <td>Pon</td><td>Wto</td><td>Śro</td><td>Czw</td><td>Pią</td><td id="weekend">Sob</td><td id="weekend">Nie</td>
              </tr>
            </thead>
            <tbody>
              <% string = tablica_miesiaca(Time.now) %>
              <% i = 0 %>
              <% string.each do |dzien| %>
                <% if i == 0 %>
                  <tr>
                <% end %>
                <% tab_day = dzien.split('|') %>
                <% if tab_day[0].to_i == Time.now.day %>
                  <td class="current-day"><%= tab_day[0] %></td>
                <% elsif i >= 5 %>
                  <td class="weekend-day"><%= tab_day[0] %></td>
                <% else %>
                  <td class="<%= tab_day[1] %>"><%= tab_day[0] %></td>
                <% end %>
                <% i += 1 %>
                <% if i == 7 %>
                  </tr>
                  <% i = 0 %>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <div class="ring-left">Na lewo</div>
          <div class="ring-right">Na prwo</div>
        </div> <!-- end calendar-container -->
      </div><!-- koniec srodkowej czesci ciala strony. -->
      
      <div class="col-xs-6 col-md-3">
       <!-- drugi miesiac -->
       
             <div class="panel panel-primary"><!-- kalendarz pierwszy -->
        <% tab_month = tablica_miesiaca(Time.now.months_ago(1)) %>
        <% tab_month.shift %>
        <div class="panel-heading"><%= data_month(Time.now.months_ago(1).month) %></div>
        <div class="panel-body">
          <table class="month-side">
            <tr>
              <td>Pon</td><td>Wto</td><td>Śro</td><td>Czw</td><td>Pią</td><td id="weekend">Sob</td><td id="weekend">Nie</td>
            </tr>
            <% i = 0 %>
        <% tab_month.each do |dzien| %>
          <% if i == 0 %>
            <tr>
          <% end %>
          <% tab_day = dzien.split('|') %>
          <% if i >= 5 %>
            <td class="weekend-day"><%= tab_day[0] %></td>
          <% else %>
            <td class="<%= tab_day[1] %>"><%= tab_day[0] %></td>
          <% end %>
          <% i += 1 %>
          <% if i == 7 %>
            </tr>
            <% i = 0 %>
          <% end %>
        <% end %>
      </table><!-- Koniec tablicy dla kalendarza drugiego -->
        </div>
      </div>

      
      <div class="panel panel-success"><!-- kalendarz drugi -->
        <% tab_month = (tablica_miesiaca(Time.now.months_since(1))) %>
        <% tab_month.shift %>
        <div class="panel-heading"><%= data_month(Time.now.months_since(1).month) %></div>
        <div class="panel-body">
          <table class="month-side">
            <tr>
              <td>Pon</td><td>Wto</td><td>Śro</td><td>Czw</td><td>Pią</td><td id="weekend">Sob</td><td id="weekend">Nie</td>
            </tr>
            <% i = 0 %>
        <% tab_month.each do |dzien| %>
          <% if i == 0 %>
            <tr>
          <% end %>
          <% tab_day = dzien.split('|') %>
          <% if i >= 5 %>
            <td class="weekend-day"><%= tab_day[0] %></td>
          <% else %>
            <td class="<%= tab_day[1] %>"><%= tab_day[0] %></td>
          <% end %>
          <% i += 1 %>
          <% if i == 7 %>
            </tr>
            <% i = 0 %>
          <% end %>
        <% end %>
      </table><!-- Koniec tablicy dla kalendarza drugiego -->
        </div>
      </div>
      
     <div class="panel panel-info">
       <div class="panel-heading">Ilość godzin:</div> 
      <div class="panel-body">
        ilość godzin: 0<br/>
        w tym nocnych: 0
      </div>
    </div>
</div>

<hr>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>Witaj na mojej stronie przykładowego grafiku pracy.</h1>
<p>Jest to aplikacja napisana we fremworku rails 4.2.5
Celem jest tworzenie grafiku miesięcznego pracy w zakładzie z podziałem 
na zmiany jak i na działy.</p>
<p>Umożliwia zchierarchizowanie stanowisk pracowników oraz póżniejszą 
kontrolę grafiku w zależności od zajmowanego stanowiska.</p>

<p>...</p>
<p>
      <%= link_to "O programie", about_path, class: 'btn btn-primary' %>
      <%= link_to "Zapisz się", '#', class: 'btn btn-primary' %>
</p>
</div>