config/routes.rb
Rails.application.routes.draw do
  resources :option_shifts
  root 'home#index'
  get 'home/index'
  get 'home/about', :as => 'about'
  get 'home/contact', :as => 'contact'
  get 'home/administaracja', :as => 'administracja'
  get 'home/kalendarz', :as => 'kalendarz'
  get 'home/grafik', as: 'grafik'
  get 'kalendarz/new', to: 'kalendarz#new'
  post 'kalendarz/new', to: 'kalendarz#create'
  get 'kalendarz/edit/:id', to: 'kalendarz#edit', as: 'kalendarz_edit'
  post 'kalendarz/edit/:id', to: 'kalendarz#update'

  resources :employees
  resources :statuses
  resources :departments
  resources :shifts do
    resources :grafiks
  end

end

app/models/shift.rb
class Shift < ActiveRecord::Base
    has_many :employees
    has_many :grafiks, dependent: :destroy
    validates_presence_of :nazwa, :message => "Musisz podać nazwę zmiany."
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    before_action :set_ships, only:[:show, :edit, :destroy, :update]
    
    def index
        @shifts = Shift.all
    end
    
    def show
    end
    
    def new
        @shift = Shift.new
    end
    
    def create
        @shift = Shift.new(shift_params)
        respond_to do |format|
            if @shift.save
                format.html {redirect_to @shift, notice: "Zmiana została zapisana"}
                format.json {render :show, status: :created, location: @shift}
            else
                format.html {render :new}
                format.json {render json: @employee.errors, status: :unprocessable_entity}
            end
        end
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
            if @shift.update(shift_params)
                format.html {redirect_to @shift, notice: "Zmiana została zaktualizowana"}
                format.json {render show, status: :ok, location: @shift}
            else
                format.html {render :edit}
                format.json { render json: @employee.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @shift.destroy
        respond_to do |format|
            format.html {redirect_to shifts_url, notice: "Zmiana została usunięta"}
            format.json {head :no_content}
        end
    end
    
    def grafik
    end
    
    private
    def set_ships
        @shift = Shift.find(params[:id])
    end
    
    def shift_params
        params.require(:shift).permit(:nazwa)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= yield(:title) %>
  </div>
  <div class="panel-body">
<%= form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <% errors_count = @shift.errors.count %>
      <% if errors_count == 1 %>
        <h2>1 błąd nie pozwala na przetworzenie formólarza:</h2>
      <% else %>
        <h2><%= errors_count %> błedy nie pozwalają na przetworzenie formólarza:</h2>
      <% end %>
      <ul>
      <% @shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
      <%= f.label :nazwa, "Nazwa zmiany:" %><br />
      <%= f.text_field :nazwa %><br />
  </div>
  <div class="action">
      <%= f.submit %>
  </div>

<% end %>
</div>
  <div class="panel-footer"><%= link_to "Powrót do listy", shifts_path %> | 
  <%= link_to "Panel administracyjny", administracja_path %></div>
</div>

app/views/shifts/edit.html.erb
<% provide(:title, "Edycja zmiany") %>
<%= render 'form' %>

app/views/shifts/grafikhtml.erb
<h1>Kalendarz</h1>
<h2><%= "Dla zmiany #{@shift.nazwa}" %></h2>
<%= form_for(:kalendarz, :action => "create") do |f| %>
    <table class="calendar">
    <thead>
        <tr>
            <td>Pon</td><td>Wto</td><td>Śro</td><td>Czw</td><td>Pią</td><td>Sob</td><td>Nie</td>
        </tr>
    </thead>
      <% @string.split('<tr>').each do |kolumna| %>
      <tr>
      <% kolumna.split.each do |dzien| %>
      <td>
      <% tmp = dzien.split('|') %>
      <%= "" %>
      <%=f.select(:kalendarz[tmp[0]], [["#{tmp[0]} wolne", '0'], ["#{tmp[0]} dniówka", '1'], ["#{tmp[0]} nocka", '2'], ["#{tmp[0]} inny miesiąc", '3']], {}, {:class=>"form-control", :style=>"opacity: 1;"}) %>

      </td>
      <% end %>
      </tr>
      <% end %>
      </table>
      <%= f.hidden_field :kalendarz[100], :value => 11 %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<%= "#{@shift}" %>
<% end %>

app/views/shifts/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel administracyjny aplikacji - Lista zmian <span class="badge"><%= Shift.count %></span></div>
  <div class="panel-body"></div>
  <!-- Table -->
  <div>
  <table class="table">
        <tr>
            <th>Nazwa Zmiany  </th>
            <th>Liczba pracowników:</th>
            <th allign="center">  Akcja:</th>
        </tr>
        <% @shifts.each do |shift| %>
          <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
              <td><%= link_to "#{shift.nazwa}", shift %></td>
              <td><%= shift.employees.count %></td>
              <td class="list_actions" > 
                  <%= link_to 'Edit' , edit_shift_path(shift) %> | 
                  <%= link_to 'Destroy' , shift,
                  :confirm => 'Jesteś pewien?' ,
                  :method => :delete %>
              </td>
          </tr>
        <% end %>
    </table>
    <div class="panel-footer"><%= link_to 'Nowa Zmiana' , new_shift_path %> |
<%= link_to "Porót do administarcji", administracja_path %></div>
</div>

app/views/shifts/new.html.erb
<% provide(:title, "Nowa zmiana") %>
<%= render 'form' %>

app/views/shifts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Zmiana:</div> 
  <div class="panel-body">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <p>
      <strong>Nazwa:</strong>
      <%= @shift.nazwa %>
    </p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Edytuj', edit_shift_path(@shift) %> | 
    <%= link_to 'Powrót do listy', shifts_path %> | 
    <%= link_to "Porót do administarcji", administracja_path %>
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">Grafik:</div>
  <div class="row">
  <div class="col-md-3">
    <% if @shift.grafiks.size > 0 %>
      <% @miesiac = Time.now.month %>
      <% @tablica_dni = @shift.grafiks.first.dane.split %>
      <%= render '/shared/grafik' %>
      <hr /><%= link_to 'Edytuj kalendarz', kalendarz_edit_path(id: @shift.grafiks.first) %>
    <% else %>
      Brak danych w grafiku
      <%= link_to 'Utwórz grafik', new_shift_grafik_path(@shift) %>
    <% end %>
  </div>
  <div class="col-md-3">
    <% if @shift.grafiks.size > 1 %>
      <% @miesiac = Time.now.months_since(1).month %>
      <% @tablica_dni = @shift.grafiks.second.dane.split %>
      <% @tablica_dni.shift %>
      <%= render "/shared/grafik" %>
      <hr /><%= link_to 'Edytuj kalendarz' , kalendarz_edit_path(id: @shift.grafiks.second)  %>
    <% else %>
      <%= link_to 'Utwórz grafik', new_shift_grafik_path(@shift) %>
    <% end %>
  </div>
  <div class="col-md-3">
    <% if @shift.grafiks.size > 2 %>
      <% @miesiac = Time.now.months_since(2).month %>
      <% @tablica_dni = @shift.grafiks.third.dane.split %>
      <% @tablica_dni.shift %>
      <%= render "/shared/grafik" %>
      <hr /><%= link_to 'Edytuj kalendarz' , kalendarz_edit_path(id: @shift.grafiks.third)  %>
    <% else %>
      <%= link_to 'Utwórz grafik', new_shift_grafik_path(@shift) %>
    <% end %>
  </div>
  <div class="col-md-3">
    <h2>Opcje kolorów</h2>
    <table>
      <% OptionShift.all.each do |opcja| %>
        <tr style="color: <%= opcja.color %>">
          <td><%= opcja.option %></td>
          <td><%= opcja.description %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="panel-footer">...</div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Lista pracowników na zmianie <%= @shift.nazwa %></h3>
  </div>
  <div class="panel-body" id="list_product">
    <table class="admin_list table">
      <tr>
        <th>Email: </th>
        <th>Dział:</th>
        <th>Status:</th>
      </tr>
      <div id="product_list">
    <% @shift.employees.each do |employee| %>
      <tr class="<%= cycle('list_line_odd' , 'list_line_even' ) %>">
        <td><%= employee.email %></td>
        <td><%= employee.department.nazwa %></td>
        <td><%= employee.status.nazwa %></td>
      </tr>
    <% end %>
    </div>
    </table>
  </div>
  <div class="panel-footer"><span class="label label-success">Pracownikó:  </span><span class="badge"><%= @shift.employees.count %></span></div>
</div>